const JWT_SECRET = process.env.JWT_SECRET!;
const JWT_EXPIRES_IN = "15m";
const REFRESH_SECRET = process.env.REFRESH_SECRET || JWT_SECRET;
const REFRESH_EXPIRES_IN = "7d";

export { JWT_EXPIRES_IN, JWT_SECRET, REFRESH_EXPIRES_IN, REFRESH_SECRET };
